version: "3.8"

services:
    # frontend:
    #     build:
    #         context: ./client
    #         dockerfile: Dockerfile
    #     container_name: react_client
    #     ports:
    #         - "3000:3000"
    #     environment:
    #         - CHOKIDAR_USEPOLLING=true
    #     volumes:
    #         - ./client:/app
    #         - /app/node_modules
    #     depends_on:
    #         - backend

    # backend:
    #     build:
    #         context: ./server
    #         dockerfile: Dockerfile
    #     container_name: express_server
    #     ports:
    #         - "5000:5000"
    #     environment:
    #         DATABASE_HOST: ${DB_HOST}
    #         DATABASE_USER: ${DB_USER}
    #         DATABASE_PASSWORD: ${DB_PASSWORD}
    #         DATABASE_NAME: ${DB_NAME}
    #     volumes:
    #         - ./server:/app
    #         - /app/node_modules
    #     depends_on:
    #         - db

    mysql:
        image: mysql:latest
        container_name: mysql_container
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3306:3306"

volumes:
    db_data:
